# -*- coding: utf-8 -*-
"""feature.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qRMW8ZC_ifj_XieH_ZTCZzqWbiudJSXX
"""

import pandas as pd

def make_features(df, freq="5min"):
    df_agg = pd.DataFrame({
        "requests": df.resample(freq).size(),
        "bytes": df["bytes"].resample(freq).sum(),
        "error_rate": df["status"].ge(400).resample(freq).mean()
    })

    # Lag features
    for lag in [1, 2, 3, 6]:
        df_agg[f"requests_lag_{lag}"] = df_agg["requests"].shift(lag)
        df_agg[f"bytes_lag_{lag}"] = df_agg["bytes"].shift(lag)

    # Rolling features
    for w in [3, 6]:
        df_agg[f"requests_roll_mean_{w}"] = df_agg["requests"].rolling(w).mean()
        df_agg[f"bytes_roll_mean_{w}"] = df_agg["bytes"].rolling(w).mean()

    # Calendar features
    df_agg["hour"] = df_agg.index.hour
    df_agg["day_of_week"] = df_agg.index.dayofweek
    df_agg["is_weekend"] = (df_agg["day_of_week"] >= 5).astype(int)

    return df_agg.dropna()