# -*- coding: utf-8 -*-
"""forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SJ_ckPIqL0G2dWmCddkHQqabs8OCI7Bi
"""

import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error

import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error

def evaluate_forecast(y_true, y_pred):
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100

    return {
        "RMSE": rmse,
        "MAE": mae,
        "MAPE": mape
    }

from statsmodels.tsa.arima.model import ARIMA
def train_arima(train_series, order=(2,1,2)):
    model = ARIMA(train_series, order=order)
    fitted = model.fit()
    return fitted

def forecast_arima(model, steps):
    forecast = model.forecast(steps=steps)
    return forecast

import xgboost as xgb
def train_xgboost(X_train, y_train, params=None):
    if params is None:
        params = {
            "n_estimators": 200,
            "max_depth": 5,
            "learning_rate": 0.05,
            "subsample": 0.8,
            "colsample_bytree": 0.8,
            "random_state": 42
        }

    model = xgb.XGBRegressor(**params)
    model.fit(X_train, y_train)
    return model

def forecast_xgboost(model, X_test):
    return model.predict(X_test)