# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/189ojL7In57Hl0KEMf0Y166GrJ5KkqdJ9
"""

import re
import pandas as pd
from datetime import datetime
from pathlib import Path

log_pattern = re.compile(
    r'(?P<host>\S+)\s+'
    r'\S+\s+\S+\s+'
    r'\[(?P<time>.*?)\]\s+'
    r'"(?P<method>\S+)\s+'
    r'(?P<url>\S+)\s*'
    r'\S*"\s+'
    r'(?P<status>\d{3})\s+'
    r'(?P<bytes>\S+)'
)

def load_and_clean_log(path):
    """
    Load raw web server log file and return a cleaned pandas DataFrame.
    """
    path = Path(path)

    records = []
    with open(path, "r", encoding="latin-1") as f:
        for line in f:
            m = log_pattern.search(line)
            if m:
                d = m.groupdict()
                d["bytes"] = int(d["bytes"]) if d["bytes"].isdigit() else 0
                d["time"] = datetime.strptime(
                    d["time"], "%d/%b/%Y:%H:%M:%S %z"
                )
                records.append(d)

    df = pd.DataFrame(records)
    df = df.set_index("time").sort_index()
    df["status"] = df["status"].astype(int)
    df["bytes"] = df["bytes"].astype("int64")

    return df